# Generated by Django 5.2.14 on 2026-05-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('improved_text', models.TextField()),
                ('suggestion_type', models.CharField(choices=[('improve', 'Text Improvement'), ('ats', 'ATS Analysis'), ('summary', 'Summary Generation'), ('skills', 'Skill Recommendation')], default='improve', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Suggestion',
                'verbose_name_plural': 'AI Suggestions',
                'db_table': 'ai_suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
